<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Api\TagController;
use App\Http\Controllers\Admin\Api\AuthController;
use App\Http\Controllers\Admin\Api\CityController;
use App\Http\Controllers\Admin\Api\SizeController;
use App\Http\Controllers\Admin\Api\BrandController;
use App\Http\Controllers\Admin\Api\ColorController;
use App\Http\Controllers\Admin\Api\OfferController;
use App\Http\Controllers\Admin\Api\PointController;
use App\Http\Controllers\Admin\Api\RolesController;
use App\Http\Controllers\Admin\Api\StateController;
use App\Http\Controllers\Admin\Api\BranchController;
use App\Http\Controllers\Admin\Api\PolicyController;
use App\Http\Controllers\Admin\Api\SliderController;
use App\Http\Controllers\Admin\Api\VendorController;
use App\Http\Controllers\Admin\Api\ProductController;
use App\Http\Controllers\Admin\Api\VoucherController;
use App\Http\Controllers\Admin\Api\CategoryController;
use App\Http\Controllers\Admin\Api\DropDownController;
use App\Http\Controllers\Admin\Api\MaterialController;
use App\Http\Controllers\Admin\Api\AdminUserController;
use App\Http\Controllers\Admin\Api\DashboardController;
use App\Http\Controllers\Admin\Api\FlashSaleController;
use App\Http\Controllers\Admin\Api\PackingUnitController;
use App\Http\Controllers\Admin\Api\DeliveryAreaController;
use App\Http\Controllers\Admin\Api\ElwekalaCollectionController;

Route::post('login', [AuthController::class, 'login']);
Route::get('dropdown/{model}', [DropDownController::class, 'index']);
Route::middleware('auth:admin-api')->group(function () {
    Route::resource('product', ProductController::class);
    Route::get('dashboard', [DashboardController::class, 'index']);
    Route::resource('users', AdminUserController::class)->names('admin.users');
    Route::resource('roles', RolesController::class)->names('admin.roles');
    Route::resource('categories', CategoryController::class);
    Route::patch('categories/{category}/toggle', [CategoryController::class, 'toggleIsActive']);
    Route::resource('materials', MaterialController::class);
    Route::patch('materials/{material}/toggle', [MaterialController::class, 'toggleIsActive']);
    Route::resource('brands', BrandController::class)->names('admin.brands');
    Route::resource('sliders', SliderController::class)->names('admin.sliders');
    Route::patch('sliders/{slider}/toggle', [SliderController::class, 'toggleIsActive']);
    Route::patch('brands/{brand}/toggle', [BrandController::class, 'toggleIsActive']);
    Route::resource('packing-units', PackingUnitController::class);
    Route::patch('packing-units/{packingUnit}/toggle', [PackingUnitController::class, 'toggleIsActive']);
    Route::resource('sizes', SizeController::class);
    Route::patch('sizes/{size}/toggle', [SizeController::class, 'toggleIsActive']);
    Route::resource('colors', ColorController::class);
    Route::patch('colors/{color}/toggle', [ColorController::class, 'toggleIsActive']);
    Route::resource('tags', TagController::class);
    Route::patch('tags/{tag}/toggle', [TagController::class, 'toggleIsActive']);
    Route::resource('states', StateController::class);
    Route::resource('cities', CityController::class);
    Route::resource('vendors', VendorController::class)->except('update');
    Route::put('vendors/storeInfo/{vendor}', [VendorController::class, 'storeInfoUpdate']);
    Route::put('vendors/ownerInfo/{vendorUser}', [VendorController::class, 'ownerInfoUpdate']);
    Route::put('vendors/douments/{vendor}', [VendorController::class, 'doumentsUpdate']);

    Route::put('vendors/storeInfo/{vendor}', [VendorController::class, 'storeInfoUpdate']);
    Route::patch('vendors/{vendor}/status', [VendorController::class, 'changeStatus']);
    Route::resource('policies', PolicyController::class);
    Route::resource('elwekala-collections', ElwekalaCollectionController::class)->names('admin.elwekala-collections')->except('destroy', 'update');
    Route::put('elwekala-collections/update', [ElwekalaCollectionController::class, 'update']);
    Route::delete('elwekala-collections/{type}', [ElwekalaCollectionController::class, 'destroy']);
    Route::resource('flash-sales', FlashSaleController::class)->names('admin.flash-sales');
    Route::resource('delivery-areas', DeliveryAreaController::class)->names('admin.delivery-areas');
    Route::resource('voucher', VoucherController::class);
    Route::resource('points', PointController::class);
    Route::patch('points/{point}/toggle-archive', [PointController::class, 'toggleArchive']);
    Route::resource('offer', OfferController::class);
    Route::resource('branchs', BranchController::class)->names('admin.branches');
});
